### ISSUE TITLE
[Android Bootcamp] Group Project: Planning - Review

### ISSUE THREAD

**Issue by lihengl** [BigPuffs/MiniPuff#1]
This is the group project repository of @israkir, @hialan, and @lihengl
Planning material can be reviewed at the `planning` branch.
/cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1:  Nice work creating wire-frames and creating stories. Great to see the basic screens and flow. Few notes to mention:

* Good to see the wireframes that cover basic flow of the app
* Good job identifying required and optional user stories
* It is important create tasks for each of your stories/features and have them assigned to team members in the form of issues.
* Once you identify tasks, consider diving a bigger parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.

**Comment by lihengl** [comment]
Finished the demo. Closing this.
